# Generated by Django 3.1.3 on 2020-11-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='zoom',
            field=models.IntegerField(default=10),
        ),
    ]
