# Generated by Django 3.1.3 on 2020-11-25 17:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0002_memory_zoom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Memory',
            new_name='Place',
        ),
    ]
